/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "color-range": {
          0: "#ffffff",
          1: "#090e1a",
          2: "#141f39",
          3: "#1b2a4d",
          4: "#1b294b",
          5: "#293d70",
          6: "#375295",
          7: "#5775c1",
          8: "#8fa3d6",
          9: "#d3daee",
        },
      },
    },
  },
  safelist: [
    "bg-color-range-0",
    "bg-color-range-1",
    "bg-color-range-2",
    "bg-color-range-3",
    "bg-color-range-4",
    "bg-color-range-5",
    "bg-color-range-6",
    "bg-color-range-7",
    "bg-color-range-8",
    "bg-color-range-9",
    "text-gray-0",
    "text-gray-100",
    "text-gray-200",
    "text-gray-300",
    "text-gray-400",
    "text-gray-500",
    "text-gray-600",
    "text-gray-700",
    "text-gray-800",
    "text-gray-900",
  ],
  plugins: [],
};
